---
title: "練習題"
author: "湯明軒 Andrew (tang@thinkerdata.com) at 析客數據有限公司"
date: "`r format(Sys.time(), '%Y/%m/%d')`"
output:
  html_document:
    toc: true
    number_sections: false
    toc_float:
      collapsed: true
---

```{r, echo=FALSE}
library(magrittr)
knitr::opts_chunk$set(echo = TRUE, cache = T, warning = F, message = F)
Sys.setenv(PATH = paste("/Users/Andrew/anaconda/bin", Sys.getenv("PATH"), sep=":"))
```


# Python入門
## list {.tabset .tabset-fade}
### Q
試著使用sum函數將整數list進行加總
```{python}
[1,2,3] #list
```


### A
```{python}
print(sum([1,2,3]))
```


## for迴圈 {.tabset .tabset-fade}
### Q
試著使用for loop及range，print整數1:5

### A
```{python}
for i in range(1,5+1):
  print(i)
```

## 自定義函數 {.tabset .tabset-fade}
### Q
請自定義一個函數：判別input為奇數或是偶數

### A
```{python}
def oddOrEven(num):
    mod = int(num) % 2
    if mod > 0:
        print("You picked an odd number.")
    else:
        print("You picked an even number.")
        
oddOrEven(9)
```

## Google評論GET {.tabset .tabset-fade}
### Q
- GET 「Google Play商店的APP評論」
- 請依下列步驟練習：
    - 打開Chrome瀏覽器，於網址列中輸入Google Play並進入其網站
    - 於Google Play中搜尋「Whos call」並進入其App內頁
    - 依照上述步驟將網頁GET下來

### A
```{python}
import requests
res_gooplay_get = requests.get('https://play.google.com/store/apps/details?id=gogolook.callgogolook2&hl=zh_TW')
print(type(res_gooplay_get))
print(dir(res_gooplay_get))
print(res_gooplay_get.text[:100])
```


## POST簡易網站 {.tabset .tabset-fade}
### Q
- 請依下列步驟練習：
    - https://www.cs.tut.fi/~jkorpela/forms/testing.html
    - 請見網頁中最下方的範例
    - 依照上述步驟找出規則
    - 用POST方法，傳送表單('Comments' : 'I love Python', 'hidden field':'R is nice also')
    - print出server端回傳的response，並且透過HTML函數將其內容重現

### A
```{python}
import requests
payload = {
    'Comments':'I love Python',
    'hidden field':'R is nice also'
}

res_simple_post2 = requests.post('http://www.tipjar.com/cgi-bin/test', data = payload)
print(res_simple_post2.text)
```

## GET Google Play Comment {.tabset .tabset-fade}
### Q
- 請依下列步驟練習：
    - 透過GET取得Google play任一APP的網頁原始碼
    - 轉換為`BeautifulSoup`物件
    - 依照上述步驟找出規則並取得user評論的list
    - 將list依序print出來

### A
```{python}
import requests
from bs4 import BeautifulSoup
res_gooplay_get = requests.get('https://play.google.com/store/apps/details?id=gogolook.callgogolook2&hl=zh_TW')
soup = BeautifulSoup(res_gooplay_get.text, 'lxml')
comments = soup.select('div[class="review-body with-review-wrapper"]')
for comment in comments[:3]: #只顯示前3筆
    print(comment.get_text())
```

## mac-benchmarks table with Pandas {.tabset .tabset-fade}
### Q
- 將「mac-benchmarks」網頁原始碼parse出表格資料
- 請依下列步驟練習：
    - 以GET方法將網頁 https://browser.primatelabs.com/mac-benchmarks 原始碼讀入
    - 依照上述步驟parse出表格資料
    - 試著只取得其機型與分數欄位
    - 以plot函數，繪製長條圖

### A
```{python}
import requests
import pandas as pd
res = requests.get("https://browser.primatelabs.com/mac-benchmarks")
import sys
dfs = pd.read_html(res.text)
df = dfs[1][["Mac", "Score"]]
print(df.head())
df.plot(kind='bar');
df.ix[:10].plot(kind='bar');
```


## parse 批批踢JOKE版的推文 with bs4 {.tabset .tabset-fade}
### Q
- 擷取並parse「批批踢JOKE版的一篇文章」
- 請依下列步驟練習：
    - 以GET方法將網頁 https://www.ptt.cc/bbs/joke/M.1464278893.A.2FE.html 原始碼讀入
    - 依照上述步驟parse出推文內容及推文者
    - 透過for迴圈，整齊印出

### A
```{python}
import requests
from bs4 import BeautifulSoup
res_ppt_get = requests.get("https://www.ptt.cc/bbs/joke/M.1464278893.A.2FE.html")

soup = BeautifulSoup(res_ppt_get.text, 'lxml')
pushs = soup.select('.push')

for push in pushs[:10]: #只印前10筆
    print(push.select('span[class="f3 hl push-userid"]')[0].text,
          push.select('span[class="f3 push-content"]')[0].text)
```

## 政府開放資料csv-1 {.tabset .tabset-fade}
### Q
- 政府開放資料：
    - 資料集描述：戶數、人口數按戶別及性別
    - 主要欄位說明：統計年、區域別、村里、戶別、戶數、男性、女性

- 步驟提示：
    - 載入資料
    - 取得資料的維度狀況
    - 預覽前5筆資料
    - 計算各欄位摘要統計值

### A
```{python}
import pandas as pd
opdat = pd.read_csv("_data/opendata105Y010.csv")
print("-----資料欄列數-----")
print(opdat.shape)
print("-----各欄位資料類別-----")
print(opdat.dtypes)
print("-----各欄位摘要-----")
print(opdat.describe())
print("-----前五筆資料-----")
print(opdat.head(5))
```

## 政府開放資料csv-2 {.tabset .tabset-fade}
### Q
- 上面的練習面臨了什麼狀況呢？(注意摘要統計值)
- 請找出方法成功的計算，數值欄位的摘要統計值
- 語法上的不熟悉很正常，給自己3分鐘的時間Google

### A
```{python}
import pandas as pd
opdat = pd.read_csv("_data/opendata105Y010.csv")
opdat.columns = opdat[:1].values.tolist()
opdat = opdat[1:]
print(opdat.ix[:,4:].astype(int).describe())

```

## 成對散點圖 {.tabset .tabset-fade}
### Q
- 任意挑選opendata103Y010資料的兩個數值欄位繪製成對散點圖

### A
```{}
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
opdat = pd.read_csv("_data/opendata103Y010.csv")
opdat.columns = opdat[:1].values.tolist()
opdat = opdat[1:]
sns.pairplot(opdat[['共同生活戶_男','共同生活戶_女']].astype(int))
plt.show()
# 中文問題：https://segmentfault.com/a/1190000005144275
```
## 集群分析 {.tabset .tabset-fade}
### Q
- 將opendata103Y010資料以k-means的**列**集為5群
- 依照上述步驟將其視覺化
- 提示：透過`apply(pd.to_numeric)`一次將多欄位轉換為數值資料
- 將labels對應地名(區域別+村里名稱)


### A
```{}
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
opdat = pd.read_csv("_data/opendata103Y010.csv")
opdat.columns = opdat[:1].values.tolist()
opdat = opdat[1:]

from sklearn.cluster import KMeans
kmeans_model = KMeans(n_clusters=5, random_state=1)
good_columns = opdat.ix[:,list(range(12))[3:]].apply(pd.to_numeric)
good_columns = good_columns._get_numeric_data().dropna(axis=1) # 移除非數值及含有NA值的欄位
kmeans_model.fit(good_columns)
labels = kmeans_model.labels_

from sklearn.decomposition import PCA
pca_2 = PCA(2)
plot_columns = pca_2.fit_transform(good_columns)
plt.scatter(x=plot_columns[:,0], y=plot_columns[:,1], c=labels)
plt.show()

pd.DataFrame({'location':opdat['區域別']+opdat['村里名稱'], 'labels':labels}).sort_values(by='labels').head()
```

## 線性迴歸-alligator資料集 {.tabset .tabset-fade}
### Q
- 將「alligator.csv」資料讀入並進行線性迴歸分析
- 美國短吻鳄
- 載入資料
- 取得資料的維度狀況
- 試以長度為自變數(x)，重量為應變數(y)，配適迴歸模型
- 繪製散點圖並將迴歸直線一同畫上

### A
```{}
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
df = pd.read_csv("_data/alligator.csv")

def f(x, a, b):
    return a*x + b

x = df.iloc[:,0]
y = df.iloc[:,1]
popt, pcov = curve_fit(f, x, y)
a, b = popt

plt.scatter(x,y)
plt.plot(x, a*x + b, 'r',label="fit")
ax = plt.gca()
ax.legend();
plt.show()
```

## 線性迴歸-廣告資料集 {.tabset .tabset-fade}
### Q
- 以Radio為自變數進行單變量線性迴歸
- 假設一個新的Radio投入成本為30，請預測其銷售量
- 繪製散點圖與迴歸直線

### A
```{}

```

